name: test run
on:
  push:
    paths:
      - "**.ts"
      - ".github/workflows/validate-master.yml"
  pull_request:
    paths:
      - "**.ts"
      - ".github/workflows/validate-master.yml"
jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup NodeJS
        uses: actions/setup-node@v2
      - run: echo "â­ï¸ NodeJS is setup on the runner"
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: yarn
      - run: yarn compile && yarn test
      - run: echo "ğŸ This job's status is ${{ job.status }}."

  test-windows:
    runs-on: windows-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup NodeJS
        uses: actions/setup-node@v2
      - run: echo "â­ï¸ NodeJS is setup on the runner"
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: yarn
      - run: yarn compile && yarn test
      - run: echo "ğŸ This job's status is ${{ job.status }}."
